/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enigma.accounting.software;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell1
 */
public class Salt_Page extends javax.swing.JFrame {
    public static int flag;
    public static String salt;
    /**
     * Creates new form Salt_Page
     * @param f
     */
    public Salt_Page(int f) {
        initComponents();
        flag=f;
        if(flag==1)
            jLabel2.setText("MODIFY SALT");
        this.dispose();
        this.setUndecorated(true);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        
        jTextField1.requestFocus(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD SALT");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("SALT : ");

        jTextField1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "This Field cannot be Empty!");
            jTextField1.requestFocus();
            jTextField1.selectAll();
        }
        else{
            Connection conn=MySqlConnect.ConnectDB();
            String sql="SELECT * FROM SALT WHERE SNAME='" +jTextField1.getText() +"';";
            try{
                Statement s=conn.createStatement();
                ResultSet rs=s.executeQuery(sql);
                if(rs.next()){
                    if(flag==0){
                        JOptionPane.showMessageDialog(null, "Salt Already Exists!");
                        jTextField1.requestFocus();
                        jTextField1.selectAll();
                    }
                    else{
                        if(!jTextField1.getText().equalsIgnoreCase(salt)){
                            JOptionPane.showMessageDialog(null, "Salt Already Exists!");
                            jTextField1.requestFocus();
                            jTextField1.selectAll();
                        }
                        else{
                            String ObjButtons[] = {"Yes","No"};
                            int PromptResult = JOptionPane.showOptionDialog(null,"Modify Salt?","SAVE?",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
                            if(PromptResult==JOptionPane.YES_OPTION){
                                String sql2="UPDATE SALT SET SNAME=? WHERE SNAME=?;";
                                PreparedStatement ps=conn.prepareCall(sql2);
                                ps.setString(1, jTextField1.getText());
                                ps.setString(2, salt);
                                ps.executeUpdate();
                                this.dispose();
                            }
                            else{
                                jTextField1.requestFocus();
                                jTextField1.selectAll();
                            }
                        }
                    }
                }
                else{
                    if(flag==0){
                        String ObjButtons[] = {"Yes","No"};
                        int PromptResult = JOptionPane.showOptionDialog(null,"Add Salt?","SAVE?",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
                        if(PromptResult==JOptionPane.YES_OPTION){
                            String sql2="INSERT INTO SALT VALUES(?);";
                            PreparedStatement ps=conn.prepareCall(sql2);
                            ps.setString(1, jTextField1.getText());
                            ps.executeUpdate();
                            this.dispose();
                        }
                        else{
                            jTextField1.requestFocus();
                            jTextField1.selectAll();
                        }
                    }
                    else{
                        String ObjButtons[] = {"Yes","No"};
                        int PromptResult = JOptionPane.showOptionDialog(null,"Modify Salt?","SAVE?",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
                        if(PromptResult==JOptionPane.YES_OPTION){
                            String sql2="UPDATE SALT SET SNAME=? WHERE SNAME=?;";
                            PreparedStatement ps=conn.prepareCall(sql2);
                            ps.setString(1, jTextField1.getText());
                            ps.setString(2, salt);
                            ps.executeUpdate();
                            this.dispose();
                        }
                        else{
                            jTextField1.requestFocus();
                            jTextField1.selectAll();
                        }
                    }
                }
            }
            catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            if(jTextField1.getText().isEmpty()){
                Salt_Page.this.dispose();
            }
            else{
                String ObjButtons[] = {"Yes","No"};
                int PromptResult = JOptionPane.showOptionDialog(null,"Exit Without Saving Changes?","EXIT?",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
                if(PromptResult==JOptionPane.YES_OPTION){
                    this.dispose();
                }
                else{
                    jTextField1.requestFocus();
                    jTextField1.selectAll();
                }
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salt_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salt_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salt_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salt_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salt_Page(flag).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
